/* input.c */
unsigned char getctrlkey(unsigned char **s);
int initkeymap(void);
void detsetallow(int _dummy);
int input(void);
int process_event(void);
int keyaction(W_Event *data);
int mkeyaction(W_Event *data);
int buttonaction(W_Event *data);
int getcourse(W_Window ww, int x, int y);
int scan(W_Window w, int x, int y);
int detmine(void);
int lockPlanetOrBase(W_Window ww, int x, int y);
int emptyKey(void);
void macro_on(void);
void doMacro(W_Event *data);
int Key32(void);
int Key33(void);
int Key34(W_Event *data);
int Key35(void);
int Key36(void);
int Key37(void);
int Key38(void);
int Key39(void);
int Key40(void);
int Key41(W_Event *data);
int Key42(void);
int Key43(void);
int Key44(void);
int Key45(void);
int Key46(void);
int Key47(void);
int Key48(void);
int Key49(void);
int Key50(void);
int Key51(void);
int Key52(void);
int Key53(void);
int Key54(void);
int Key55(void);
int Key56(void);
int Key57(void);
int Key58(void);
int Key59(W_Event *data);
int Key60(void);
int Key61(void);
int Key62(void);
int Key63(void);
int Key64(void);
int Key65(W_Event *data);
int Key66(void);
int Key67(void);
int Key68(void);
int Key69(W_Event *data);
int Key70(W_Event *data);
int Key71(W_Event *data);
int Key72(W_Event *data);
int Key73(W_Event *data);
int Key74(W_Event *data);
int Key75(void);
int Key76(void);
int Key77(W_Event *data);
int Key78(void);
int Key79(void);
int Key80(void);
int Key81(void);
int Key82(void);
int Key83(void);
int Key84(W_Event *data);
int Key85(void);
int Key86(void);
int Key87(W_Event *data);
int Key88(void);
int Key89(W_Event *data);
int Key90(W_Event *data);
int Key91(void);
int Key92(void);
int Key93(void);
int Key94(W_Event *data);
int Key95(W_Event *data);
int Key96(void);
int Key97(W_Event *data);
int Key98(void);
int Key99(void);
int Key100(void);
int Key101(void);
int Key102(W_Event *data);
int Key103(W_Event *data);
int Key104(void);
int Key105(W_Event *data);
int Key106(W_Event *data);
int Key107(W_Event *data);
int Key108(W_Event *data);
int Key109(void);
int Key110(W_Event *data);
int Key111(void);
int Key112(W_Event *data);
int Key113(void);
int Key114(void);
int Key115(void);
int Key116(W_Event *data);
int Key117(void);
int Key118(W_Event *data);
int Key119(void);
int Key120(void);
int Key121(W_Event *data);
int Key122(void);
int Key123(void);
int Key124(void);
int Key125(void);
int Key126(W_Event *data);
int Key127(W_Event *data);
int reread_defaults(void);
int Key180(W_Event *data);
int Key212(W_Event *data);
int Key207(W_Event *data);
int Key194(W_Event *data);
int Key195(W_Event *data);
int Key145(W_Event *data);
int Key146(W_Event *data);
int Key147(W_Event *data);
int Key148(W_Event *data);
int Key197(W_Event *data);
int Key208(W_Event *data);
int Key205(W_Event *data);
int Key204(W_Event *data);
int Key175(W_Event *data);
int Key162(W_Event *data);
int Key163(W_Event *data);
int Key149(W_Event *data);
int Key150(W_Event *data);
int Key151(W_Event *data);
int Key152(W_Event *data);
int Key198(W_Event *data);
int Key206(W_Event *data);
int Key200(W_Event *data);
int Key153(W_Event *data);
int Key144(W_Event *data);
int Key160(W_Event *data);
int Key131(W_Event *data);
