/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jri.h"

/* Stubs for class java/lang/String */

#ifdef IMPLEMENT_java_lang_String
#define _implementing_java_lang_String
#endif /* IMPLEMENT_java_lang_String */
#define IMPLEMENT_java_lang_String
#include "java_lang_String.h"

#ifndef UNUSED_java_lang_String_value
JRIFieldID FAR fieldID_java_lang_String_value = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jref)
get_java_lang_String_value(JRIEnv* env, struct java_lang_String* obj) {
	if (fieldID_java_lang_String_value == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_String(env) before accessing field value [C");
	}
	return (jref)
		JRI_GetField(env, obj, fieldID_java_lang_String_value);
}
JRI_PUBLIC_API(void)
set_java_lang_String_value(JRIEnv* env, struct java_lang_String* obj, jref v) {
	if (fieldID_java_lang_String_value == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_String(env) before accessing field value [C");
	}
	JRI_SetField(env, obj, fieldID_java_lang_String_value, v);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_String_value */

#ifndef UNUSED_java_lang_String_offset
JRIFieldID FAR fieldID_java_lang_String_offset = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jint)
get_java_lang_String_offset(JRIEnv* env, struct java_lang_String* obj) {
	if (fieldID_java_lang_String_offset == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_String(env) before accessing field offset I");
	}
	return JRI_GetFieldInt(env, obj, fieldID_java_lang_String_offset);
}
JRI_PUBLIC_API(void)
set_java_lang_String_offset(JRIEnv* env, struct java_lang_String* obj, jint v) {
	if (fieldID_java_lang_String_offset == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_String(env) before accessing field offset I");
	}
	JRI_SetFieldInt(env, obj, fieldID_java_lang_String_offset, v);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_String_offset */

#ifndef UNUSED_java_lang_String_count
JRIFieldID FAR fieldID_java_lang_String_count = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jint)
get_java_lang_String_count(JRIEnv* env, struct java_lang_String* obj) {
	if (fieldID_java_lang_String_count == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_String(env) before accessing field count I");
	}
	return JRI_GetFieldInt(env, obj, fieldID_java_lang_String_count);
}
JRI_PUBLIC_API(void)
set_java_lang_String_count(JRIEnv* env, struct java_lang_String* obj, jint v) {
	if (fieldID_java_lang_String_count == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_String(env) before accessing field count I");
	}
	JRI_SetFieldInt(env, obj, fieldID_java_lang_String_count, v);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_String_count */

#ifndef UNUSED_java_lang_String_InternSet
JRIFieldID FAR fieldID_java_lang_String_InternSet = JRIUninitialized;
#ifdef DEBUG
struct java_util_Hashtable;
JRI_PUBLIC_API(struct java_util_Hashtable *)
get_java_lang_String_InternSet(JRIEnv* env, struct java_lang_Class* clazz) {
	if (fieldID_java_lang_String_InternSet == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_String(env) before accessing field InternSet Ljava/util/Hashtable;");
	}
	return (struct java_util_Hashtable *)
		JRI_GetStaticField(env, clazz, fieldID_java_lang_String_InternSet);
}
JRI_PUBLIC_API(void)
set_java_lang_String_InternSet(JRIEnv* env, struct java_lang_Class* clazz, struct java_util_Hashtable * v) {
	if (fieldID_java_lang_String_InternSet == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_String(env) before accessing field InternSet Ljava/util/Hashtable;");
	}
	JRI_SetStaticField(env, clazz, fieldID_java_lang_String_InternSet, v);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_String_InternSet */

#ifndef UNUSED_java_lang_String_new
JRIMethodID FAR methodID_java_lang_String_new = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct java_lang_String*)
java_lang_String_new(JRIEnv* env, struct java_lang_Class* clazz) {
	if (methodID_java_lang_String_new == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_String(env) before calling method <init> ()V");
	}
	return (struct java_lang_String*)JRI_NewObject(env)(env, JRI_NewObject_op, clazz, methodID_java_lang_String_new);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_String_new */

#ifndef UNUSED_java_lang_String_new_1
JRIMethodID FAR methodID_java_lang_String_new_1 = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct java_lang_String*)
java_lang_String_new_1(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_String *a) {
	if (methodID_java_lang_String_new_1 == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_String(env) before calling method <init> (Ljava/lang/String;)V");
	}
	return (struct java_lang_String*)JRI_NewObject(env)(env, JRI_NewObject_op, clazz, methodID_java_lang_String_new_1, a);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_String_new_1 */

#ifndef UNUSED_java_lang_String_new_2
JRIMethodID FAR methodID_java_lang_String_new_2 = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct java_lang_String*)
java_lang_String_new_2(JRIEnv* env, struct java_lang_Class* clazz, jcharArray a) {
	if (methodID_java_lang_String_new_2 == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_String(env) before calling method <init> ([C)V");
	}
	return (struct java_lang_String*)JRI_NewObject(env)(env, JRI_NewObject_op, clazz, methodID_java_lang_String_new_2, a);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_String_new_2 */

#ifndef UNUSED_java_lang_String_new_3
JRIMethodID FAR methodID_java_lang_String_new_3 = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct java_lang_String*)
java_lang_String_new_3(JRIEnv* env, struct java_lang_Class* clazz, jcharArray a, jint b, jint c) {
	if (methodID_java_lang_String_new_3 == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_String(env) before calling method <init> ([CII)V");
	}
	return (struct java_lang_String*)JRI_NewObject(env)(env, JRI_NewObject_op, clazz, methodID_java_lang_String_new_3, a, b, c);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_String_new_3 */

#ifndef UNUSED_java_lang_String_new_4
JRIMethodID FAR methodID_java_lang_String_new_4 = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct java_lang_String*)
java_lang_String_new_4(JRIEnv* env, struct java_lang_Class* clazz, jbyteArray a, jint b, jint c, jint d) {
	if (methodID_java_lang_String_new_4 == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_String(env) before calling method <init> ([BIII)V");
	}
	return (struct java_lang_String*)JRI_NewObject(env)(env, JRI_NewObject_op, clazz, methodID_java_lang_String_new_4, a, b, c, d);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_String_new_4 */

#ifndef UNUSED_java_lang_String_new_5
JRIMethodID FAR methodID_java_lang_String_new_5 = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct java_lang_String*)
java_lang_String_new_5(JRIEnv* env, struct java_lang_Class* clazz, jbyteArray a, jint b) {
	if (methodID_java_lang_String_new_5 == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_String(env) before calling method <init> ([BI)V");
	}
	return (struct java_lang_String*)JRI_NewObject(env)(env, JRI_NewObject_op, clazz, methodID_java_lang_String_new_5, a, b);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_String_new_5 */

#ifndef UNUSED_java_lang_String_new_6
JRIMethodID FAR methodID_java_lang_String_new_6 = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct java_lang_String*)
java_lang_String_new_6(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_StringBuffer *a) {
	if (methodID_java_lang_String_new_6 == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_String(env) before calling method <init> (Ljava/lang/StringBuffer;)V");
	}
	return (struct java_lang_String*)JRI_NewObject(env)(env, JRI_NewObject_op, clazz, methodID_java_lang_String_new_6, a);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_String_new_6 */

#ifndef UNUSED_java_lang_String_new_7
JRIMethodID FAR methodID_java_lang_String_new_7 = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct java_lang_String*)
java_lang_String_new_7(JRIEnv* env, struct java_lang_Class* clazz, jint a, jint b, jcharArray c) {
	if (methodID_java_lang_String_new_7 == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_String(env) before calling method <init> (II[C)V");
	}
	return (struct java_lang_String*)JRI_NewObject(env)(env, JRI_NewObject_op, clazz, methodID_java_lang_String_new_7, a, b, c);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_String_new_7 */

#ifndef UNUSED_java_lang_String_length
JRIMethodID FAR methodID_java_lang_String_length = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jint)
java_lang_String_length(JRIEnv* env, struct java_lang_String* self) {
	if (methodID_java_lang_String_length == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_String(env) before calling method length ()I");
	}
	return (jint)JRI_CallMethodInt(env)(env, JRI_CallMethod_op, self, methodID_java_lang_String_length);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_String_length */

#ifndef UNUSED_java_lang_String_charAt
JRIMethodID FAR methodID_java_lang_String_charAt = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jchar)
java_lang_String_charAt(JRIEnv* env, struct java_lang_String* self, jint a) {
	if (methodID_java_lang_String_charAt == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_String(env) before calling method charAt (I)C");
	}
	return (jchar)JRI_CallMethodChar(env)(env, JRI_CallMethod_op, self, methodID_java_lang_String_charAt, a);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_String_charAt */

#ifndef UNUSED_java_lang_String_getChars
JRIMethodID FAR methodID_java_lang_String_getChars = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
java_lang_String_getChars(JRIEnv* env, struct java_lang_String* self, jint a, jint b, jcharArray c, jint d) {
	if (methodID_java_lang_String_getChars == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_String(env) before calling method getChars (II[CI)V");
	}
	(void)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_java_lang_String_getChars, a, b, c, d);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_String_getChars */

#ifndef UNUSED_java_lang_String_getBytes
JRIMethodID FAR methodID_java_lang_String_getBytes = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
java_lang_String_getBytes(JRIEnv* env, struct java_lang_String* self, jint a, jint b, jbyteArray c, jint d) {
	if (methodID_java_lang_String_getBytes == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_String(env) before calling method getBytes (II[BI)V");
	}
	(void)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_java_lang_String_getBytes, a, b, c, d);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_String_getBytes */

#ifndef UNUSED_java_lang_String_equals
JRIMethodID FAR methodID_java_lang_String_equals = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jbool)
java_lang_String_equals(JRIEnv* env, struct java_lang_String* self, struct java_lang_Object *a) {
	if (methodID_java_lang_String_equals == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_String(env) before calling method equals (Ljava/lang/Object;)Z");
	}
	return (jbool)JRI_CallMethodBoolean(env)(env, JRI_CallMethod_op, self, methodID_java_lang_String_equals, a);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_String_equals */

#ifndef UNUSED_java_lang_String_equalsIgnoreCase
JRIMethodID FAR methodID_java_lang_String_equalsIgnoreCase = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jbool)
java_lang_String_equalsIgnoreCase(JRIEnv* env, struct java_lang_String* self, struct java_lang_String *a) {
	if (methodID_java_lang_String_equalsIgnoreCase == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_String(env) before calling method equalsIgnoreCase (Ljava/lang/String;)Z");
	}
	return (jbool)JRI_CallMethodBoolean(env)(env, JRI_CallMethod_op, self, methodID_java_lang_String_equalsIgnoreCase, a);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_String_equalsIgnoreCase */

#ifndef UNUSED_java_lang_String_compareTo
JRIMethodID FAR methodID_java_lang_String_compareTo = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jint)
java_lang_String_compareTo(JRIEnv* env, struct java_lang_String* self, struct java_lang_String *a) {
	if (methodID_java_lang_String_compareTo == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_String(env) before calling method compareTo (Ljava/lang/String;)I");
	}
	return (jint)JRI_CallMethodInt(env)(env, JRI_CallMethod_op, self, methodID_java_lang_String_compareTo, a);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_String_compareTo */

#ifndef UNUSED_java_lang_String_regionMatches
JRIMethodID FAR methodID_java_lang_String_regionMatches = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jbool)
java_lang_String_regionMatches(JRIEnv* env, struct java_lang_String* self, jint a, struct java_lang_String *b, jint c, jint d) {
	if (methodID_java_lang_String_regionMatches == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_String(env) before calling method regionMatches (ILjava/lang/String;II)Z");
	}
	return (jbool)JRI_CallMethodBoolean(env)(env, JRI_CallMethod_op, self, methodID_java_lang_String_regionMatches, a, b, c, d);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_String_regionMatches */

#ifndef UNUSED_java_lang_String_regionMatches_1
JRIMethodID FAR methodID_java_lang_String_regionMatches_1 = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jbool)
java_lang_String_regionMatches_1(JRIEnv* env, struct java_lang_String* self, jbool a, jint b, struct java_lang_String *c, jint d, jint e) {
	if (methodID_java_lang_String_regionMatches_1 == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_String(env) before calling method regionMatches (ZILjava/lang/String;II)Z");
	}
	return (jbool)JRI_CallMethodBoolean(env)(env, JRI_CallMethod_op, self, methodID_java_lang_String_regionMatches_1, a, b, c, d, e);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_String_regionMatches_1 */

#ifndef UNUSED_java_lang_String_startsWith
JRIMethodID FAR methodID_java_lang_String_startsWith = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jbool)
java_lang_String_startsWith(JRIEnv* env, struct java_lang_String* self, struct java_lang_String *a, jint b) {
	if (methodID_java_lang_String_startsWith == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_String(env) before calling method startsWith (Ljava/lang/String;I)Z");
	}
	return (jbool)JRI_CallMethodBoolean(env)(env, JRI_CallMethod_op, self, methodID_java_lang_String_startsWith, a, b);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_String_startsWith */

#ifndef UNUSED_java_lang_String_startsWith_1
JRIMethodID FAR methodID_java_lang_String_startsWith_1 = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jbool)
java_lang_String_startsWith_1(JRIEnv* env, struct java_lang_String* self, struct java_lang_String *a) {
	if (methodID_java_lang_String_startsWith_1 == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_String(env) before calling method startsWith (Ljava/lang/String;)Z");
	}
	return (jbool)JRI_CallMethodBoolean(env)(env, JRI_CallMethod_op, self, methodID_java_lang_String_startsWith_1, a);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_String_startsWith_1 */

#ifndef UNUSED_java_lang_String_endsWith
JRIMethodID FAR methodID_java_lang_String_endsWith = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jbool)
java_lang_String_endsWith(JRIEnv* env, struct java_lang_String* self, struct java_lang_String *a) {
	if (methodID_java_lang_String_endsWith == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_String(env) before calling method endsWith (Ljava/lang/String;)Z");
	}
	return (jbool)JRI_CallMethodBoolean(env)(env, JRI_CallMethod_op, self, methodID_java_lang_String_endsWith, a);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_String_endsWith */

#ifndef UNUSED_java_lang_String_hashCode
JRIMethodID FAR methodID_java_lang_String_hashCode = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jint)
java_lang_String_hashCode(JRIEnv* env, struct java_lang_String* self) {
	if (methodID_java_lang_String_hashCode == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_String(env) before calling method hashCode ()I");
	}
	return (jint)JRI_CallMethodInt(env)(env, JRI_CallMethod_op, self, methodID_java_lang_String_hashCode);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_String_hashCode */

#ifndef UNUSED_java_lang_String_indexOf
JRIMethodID FAR methodID_java_lang_String_indexOf = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jint)
java_lang_String_indexOf(JRIEnv* env, struct java_lang_String* self, jint a) {
	if (methodID_java_lang_String_indexOf == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_String(env) before calling method indexOf (I)I");
	}
	return (jint)JRI_CallMethodInt(env)(env, JRI_CallMethod_op, self, methodID_java_lang_String_indexOf, a);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_String_indexOf */

#ifndef UNUSED_java_lang_String_indexOf_1
JRIMethodID FAR methodID_java_lang_String_indexOf_1 = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jint)
java_lang_String_indexOf_1(JRIEnv* env, struct java_lang_String* self, jint a, jint b) {
	if (methodID_java_lang_String_indexOf_1 == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_String(env) before calling method indexOf (II)I");
	}
	return (jint)JRI_CallMethodInt(env)(env, JRI_CallMethod_op, self, methodID_java_lang_String_indexOf_1, a, b);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_String_indexOf_1 */

#ifndef UNUSED_java_lang_String_lastIndexOf
JRIMethodID FAR methodID_java_lang_String_lastIndexOf = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jint)
java_lang_String_lastIndexOf(JRIEnv* env, struct java_lang_String* self, jint a) {
	if (methodID_java_lang_String_lastIndexOf == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_String(env) before calling method lastIndexOf (I)I");
	}
	return (jint)JRI_CallMethodInt(env)(env, JRI_CallMethod_op, self, methodID_java_lang_String_lastIndexOf, a);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_String_lastIndexOf */

#ifndef UNUSED_java_lang_String_lastIndexOf_1
JRIMethodID FAR methodID_java_lang_String_lastIndexOf_1 = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jint)
java_lang_String_lastIndexOf_1(JRIEnv* env, struct java_lang_String* self, jint a, jint b) {
	if (methodID_java_lang_String_lastIndexOf_1 == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_String(env) before calling method lastIndexOf (II)I");
	}
	return (jint)JRI_CallMethodInt(env)(env, JRI_CallMethod_op, self, methodID_java_lang_String_lastIndexOf_1, a, b);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_String_lastIndexOf_1 */

#ifndef UNUSED_java_lang_String_indexOf_2
JRIMethodID FAR methodID_java_lang_String_indexOf_2 = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jint)
java_lang_String_indexOf_2(JRIEnv* env, struct java_lang_String* self, struct java_lang_String *a) {
	if (methodID_java_lang_String_indexOf_2 == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_String(env) before calling method indexOf (Ljava/lang/String;)I");
	}
	return (jint)JRI_CallMethodInt(env)(env, JRI_CallMethod_op, self, methodID_java_lang_String_indexOf_2, a);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_String_indexOf_2 */

#ifndef UNUSED_java_lang_String_indexOf_3
JRIMethodID FAR methodID_java_lang_String_indexOf_3 = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jint)
java_lang_String_indexOf_3(JRIEnv* env, struct java_lang_String* self, struct java_lang_String *a, jint b) {
	if (methodID_java_lang_String_indexOf_3 == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_String(env) before calling method indexOf (Ljava/lang/String;I)I");
	}
	return (jint)JRI_CallMethodInt(env)(env, JRI_CallMethod_op, self, methodID_java_lang_String_indexOf_3, a, b);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_String_indexOf_3 */

#ifndef UNUSED_java_lang_String_lastIndexOf_2
JRIMethodID FAR methodID_java_lang_String_lastIndexOf_2 = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jint)
java_lang_String_lastIndexOf_2(JRIEnv* env, struct java_lang_String* self, struct java_lang_String *a) {
	if (methodID_java_lang_String_lastIndexOf_2 == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_String(env) before calling method lastIndexOf (Ljava/lang/String;)I");
	}
	return (jint)JRI_CallMethodInt(env)(env, JRI_CallMethod_op, self, methodID_java_lang_String_lastIndexOf_2, a);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_String_lastIndexOf_2 */

#ifndef UNUSED_java_lang_String_lastIndexOf_3
JRIMethodID FAR methodID_java_lang_String_lastIndexOf_3 = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jint)
java_lang_String_lastIndexOf_3(JRIEnv* env, struct java_lang_String* self, struct java_lang_String *a, jint b) {
	if (methodID_java_lang_String_lastIndexOf_3 == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_String(env) before calling method lastIndexOf (Ljava/lang/String;I)I");
	}
	return (jint)JRI_CallMethodInt(env)(env, JRI_CallMethod_op, self, methodID_java_lang_String_lastIndexOf_3, a, b);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_String_lastIndexOf_3 */

#ifndef UNUSED_java_lang_String_substring
JRIMethodID FAR methodID_java_lang_String_substring = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct java_lang_String *)
java_lang_String_substring(JRIEnv* env, struct java_lang_String* self, jint a) {
	if (methodID_java_lang_String_substring == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_String(env) before calling method substring (I)Ljava/lang/String;");
	}
	return (struct java_lang_String *)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_java_lang_String_substring, a);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_String_substring */

#ifndef UNUSED_java_lang_String_substring_1
JRIMethodID FAR methodID_java_lang_String_substring_1 = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct java_lang_String *)
java_lang_String_substring_1(JRIEnv* env, struct java_lang_String* self, jint a, jint b) {
	if (methodID_java_lang_String_substring_1 == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_String(env) before calling method substring (II)Ljava/lang/String;");
	}
	return (struct java_lang_String *)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_java_lang_String_substring_1, a, b);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_String_substring_1 */

#ifndef UNUSED_java_lang_String_concat
JRIMethodID FAR methodID_java_lang_String_concat = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct java_lang_String *)
java_lang_String_concat(JRIEnv* env, struct java_lang_String* self, struct java_lang_String *a) {
	if (methodID_java_lang_String_concat == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_String(env) before calling method concat (Ljava/lang/String;)Ljava/lang/String;");
	}
	return (struct java_lang_String *)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_java_lang_String_concat, a);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_String_concat */

#ifndef UNUSED_java_lang_String_replace
JRIMethodID FAR methodID_java_lang_String_replace = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct java_lang_String *)
java_lang_String_replace(JRIEnv* env, struct java_lang_String* self, jchar a, jchar b) {
	if (methodID_java_lang_String_replace == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_String(env) before calling method replace (CC)Ljava/lang/String;");
	}
	return (struct java_lang_String *)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_java_lang_String_replace, a, b);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_String_replace */

#ifndef UNUSED_java_lang_String_toLowerCase
JRIMethodID FAR methodID_java_lang_String_toLowerCase = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct java_lang_String *)
java_lang_String_toLowerCase(JRIEnv* env, struct java_lang_String* self) {
	if (methodID_java_lang_String_toLowerCase == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_String(env) before calling method toLowerCase ()Ljava/lang/String;");
	}
	return (struct java_lang_String *)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_java_lang_String_toLowerCase);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_String_toLowerCase */

#ifndef UNUSED_java_lang_String_toUpperCase
JRIMethodID FAR methodID_java_lang_String_toUpperCase = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct java_lang_String *)
java_lang_String_toUpperCase(JRIEnv* env, struct java_lang_String* self) {
	if (methodID_java_lang_String_toUpperCase == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_String(env) before calling method toUpperCase ()Ljava/lang/String;");
	}
	return (struct java_lang_String *)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_java_lang_String_toUpperCase);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_String_toUpperCase */

#ifndef UNUSED_java_lang_String_trim
JRIMethodID FAR methodID_java_lang_String_trim = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct java_lang_String *)
java_lang_String_trim(JRIEnv* env, struct java_lang_String* self) {
	if (methodID_java_lang_String_trim == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_String(env) before calling method trim ()Ljava/lang/String;");
	}
	return (struct java_lang_String *)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_java_lang_String_trim);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_String_trim */

#ifndef UNUSED_java_lang_String_toString
JRIMethodID FAR methodID_java_lang_String_toString = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct java_lang_String *)
java_lang_String_toString(JRIEnv* env, struct java_lang_String* self) {
	if (methodID_java_lang_String_toString == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_String(env) before calling method toString ()Ljava/lang/String;");
	}
	return (struct java_lang_String *)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_java_lang_String_toString);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_String_toString */

#ifndef UNUSED_java_lang_String_toCharArray
JRIMethodID FAR methodID_java_lang_String_toCharArray = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jref)
java_lang_String_toCharArray(JRIEnv* env, struct java_lang_String* self) {
	if (methodID_java_lang_String_toCharArray == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_String(env) before calling method toCharArray ()[C");
	}
	return (jref)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_java_lang_String_toCharArray);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_String_toCharArray */

#ifndef UNUSED_java_lang_String_valueOf
JRIMethodID FAR methodID_java_lang_String_valueOf = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct java_lang_String *)
java_lang_String_valueOf(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_Object *a) {
	if (methodID_java_lang_String_valueOf == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_String(env) before calling method valueOf (Ljava/lang/Object;)Ljava/lang/String;");
	}
	return (struct java_lang_String *)JRI_CallStaticMethod(env)(env, JRI_CallStaticMethod_op, clazz, methodID_java_lang_String_valueOf, a);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_String_valueOf */

#ifndef UNUSED_java_lang_String_valueOf_1
JRIMethodID FAR methodID_java_lang_String_valueOf_1 = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct java_lang_String *)
java_lang_String_valueOf_1(JRIEnv* env, struct java_lang_Class* clazz, jcharArray a) {
	if (methodID_java_lang_String_valueOf_1 == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_String(env) before calling method valueOf ([C)Ljava/lang/String;");
	}
	return (struct java_lang_String *)JRI_CallStaticMethod(env)(env, JRI_CallStaticMethod_op, clazz, methodID_java_lang_String_valueOf_1, a);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_String_valueOf_1 */

#ifndef UNUSED_java_lang_String_valueOf_2
JRIMethodID FAR methodID_java_lang_String_valueOf_2 = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct java_lang_String *)
java_lang_String_valueOf_2(JRIEnv* env, struct java_lang_Class* clazz, jcharArray a, jint b, jint c) {
	if (methodID_java_lang_String_valueOf_2 == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_String(env) before calling method valueOf ([CII)Ljava/lang/String;");
	}
	return (struct java_lang_String *)JRI_CallStaticMethod(env)(env, JRI_CallStaticMethod_op, clazz, methodID_java_lang_String_valueOf_2, a, b, c);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_String_valueOf_2 */

#ifndef UNUSED_java_lang_String_copyValueOf
JRIMethodID FAR methodID_java_lang_String_copyValueOf = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct java_lang_String *)
java_lang_String_copyValueOf(JRIEnv* env, struct java_lang_Class* clazz, jcharArray a, jint b, jint c) {
	if (methodID_java_lang_String_copyValueOf == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_String(env) before calling method copyValueOf ([CII)Ljava/lang/String;");
	}
	return (struct java_lang_String *)JRI_CallStaticMethod(env)(env, JRI_CallStaticMethod_op, clazz, methodID_java_lang_String_copyValueOf, a, b, c);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_String_copyValueOf */

#ifndef UNUSED_java_lang_String_copyValueOf_1
JRIMethodID FAR methodID_java_lang_String_copyValueOf_1 = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct java_lang_String *)
java_lang_String_copyValueOf_1(JRIEnv* env, struct java_lang_Class* clazz, jcharArray a) {
	if (methodID_java_lang_String_copyValueOf_1 == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_String(env) before calling method copyValueOf ([C)Ljava/lang/String;");
	}
	return (struct java_lang_String *)JRI_CallStaticMethod(env)(env, JRI_CallStaticMethod_op, clazz, methodID_java_lang_String_copyValueOf_1, a);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_String_copyValueOf_1 */

#ifndef UNUSED_java_lang_String_valueOf_3
JRIMethodID FAR methodID_java_lang_String_valueOf_3 = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct java_lang_String *)
java_lang_String_valueOf_3(JRIEnv* env, struct java_lang_Class* clazz, jbool a) {
	if (methodID_java_lang_String_valueOf_3 == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_String(env) before calling method valueOf (Z)Ljava/lang/String;");
	}
	return (struct java_lang_String *)JRI_CallStaticMethod(env)(env, JRI_CallStaticMethod_op, clazz, methodID_java_lang_String_valueOf_3, a);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_String_valueOf_3 */

#ifndef UNUSED_java_lang_String_valueOf_4
JRIMethodID FAR methodID_java_lang_String_valueOf_4 = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct java_lang_String *)
java_lang_String_valueOf_4(JRIEnv* env, struct java_lang_Class* clazz, jchar a) {
	if (methodID_java_lang_String_valueOf_4 == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_String(env) before calling method valueOf (C)Ljava/lang/String;");
	}
	return (struct java_lang_String *)JRI_CallStaticMethod(env)(env, JRI_CallStaticMethod_op, clazz, methodID_java_lang_String_valueOf_4, a);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_String_valueOf_4 */

#ifndef UNUSED_java_lang_String_valueOf_5
JRIMethodID FAR methodID_java_lang_String_valueOf_5 = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct java_lang_String *)
java_lang_String_valueOf_5(JRIEnv* env, struct java_lang_Class* clazz, jint a) {
	if (methodID_java_lang_String_valueOf_5 == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_String(env) before calling method valueOf (I)Ljava/lang/String;");
	}
	return (struct java_lang_String *)JRI_CallStaticMethod(env)(env, JRI_CallStaticMethod_op, clazz, methodID_java_lang_String_valueOf_5, a);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_String_valueOf_5 */

#ifndef UNUSED_java_lang_String_valueOf_6
JRIMethodID FAR methodID_java_lang_String_valueOf_6 = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct java_lang_String *)
java_lang_String_valueOf_6(JRIEnv* env, struct java_lang_Class* clazz, jlong a) {
	if (methodID_java_lang_String_valueOf_6 == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_String(env) before calling method valueOf (J)Ljava/lang/String;");
	}
	return (struct java_lang_String *)JRI_CallStaticMethod(env)(env, JRI_CallStaticMethod_op, clazz, methodID_java_lang_String_valueOf_6, a);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_String_valueOf_6 */

#ifndef UNUSED_java_lang_String_valueOf_7
JRIMethodID FAR methodID_java_lang_String_valueOf_7 = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct java_lang_String *)
java_lang_String_valueOf_7(JRIEnv* env, struct java_lang_Class* clazz, jfloat a) {
	if (methodID_java_lang_String_valueOf_7 == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_String(env) before calling method valueOf (F)Ljava/lang/String;");
	}
	return (struct java_lang_String *)JRI_CallStaticMethod(env)(env, JRI_CallStaticMethod_op, clazz, methodID_java_lang_String_valueOf_7, a);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_String_valueOf_7 */

#ifndef UNUSED_java_lang_String_valueOf_8
JRIMethodID FAR methodID_java_lang_String_valueOf_8 = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct java_lang_String *)
java_lang_String_valueOf_8(JRIEnv* env, struct java_lang_Class* clazz, jdouble a) {
	if (methodID_java_lang_String_valueOf_8 == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_String(env) before calling method valueOf (D)Ljava/lang/String;");
	}
	return (struct java_lang_String *)JRI_CallStaticMethod(env)(env, JRI_CallStaticMethod_op, clazz, methodID_java_lang_String_valueOf_8, a);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_String_valueOf_8 */

#ifndef UNUSED_java_lang_String_intern
JRIMethodID FAR methodID_java_lang_String_intern = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct java_lang_String *)
java_lang_String_intern(JRIEnv* env, struct java_lang_String* self) {
	if (methodID_java_lang_String_intern == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_String(env) before calling method intern ()Ljava/lang/String;");
	}
	return (struct java_lang_String *)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_java_lang_String_intern);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_String_intern */

#ifndef UNUSED_java_lang_String_utfLength
JRIMethodID FAR methodID_java_lang_String_utfLength = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jint)
java_lang_String_utfLength(JRIEnv* env, struct java_lang_String* self) {
	if (methodID_java_lang_String_utfLength == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_String(env) before calling method utfLength ()I");
	}
	return (jint)JRI_CallMethodInt(env)(env, JRI_CallMethod_op, self, methodID_java_lang_String_utfLength);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_String_utfLength */

#ifndef UNUSED_use_java_lang_String

static jglobal _globalclass_java_lang_String = NULL;

JRI_PUBLIC_API(struct java_lang_Class*)
use_java_lang_String(JRIEnv* env)
{
	if (_globalclass_java_lang_String == NULL) {
		struct java_lang_Class* clazz = JRI_FindClass(env, classname_java_lang_String);
		if (clazz == NULL) {
			JRI_ThrowNew(env, JRI_FindClass(env, "java/lang/ClassNotFoundException"), classname_java_lang_String);
			return NULL;
		}
		use_java_lang_String_value(env, clazz);
		use_java_lang_String_offset(env, clazz);
		use_java_lang_String_count(env, clazz);
		use_java_lang_String_InternSet(env, clazz);
		use_java_lang_String_new(env, clazz);
		use_java_lang_String_new_1(env, clazz);
		use_java_lang_String_new_2(env, clazz);
		use_java_lang_String_new_3(env, clazz);
		use_java_lang_String_new_4(env, clazz);
		use_java_lang_String_new_5(env, clazz);
		use_java_lang_String_new_6(env, clazz);
		use_java_lang_String_new_7(env, clazz);
		use_java_lang_String_length(env, clazz);
		use_java_lang_String_charAt(env, clazz);
		use_java_lang_String_getChars(env, clazz);
		use_java_lang_String_getBytes(env, clazz);
		use_java_lang_String_equals(env, clazz);
		use_java_lang_String_equalsIgnoreCase(env, clazz);
		use_java_lang_String_compareTo(env, clazz);
		use_java_lang_String_regionMatches(env, clazz);
		use_java_lang_String_regionMatches_1(env, clazz);
		use_java_lang_String_startsWith(env, clazz);
		use_java_lang_String_startsWith_1(env, clazz);
		use_java_lang_String_endsWith(env, clazz);
		use_java_lang_String_hashCode(env, clazz);
		use_java_lang_String_indexOf(env, clazz);
		use_java_lang_String_indexOf_1(env, clazz);
		use_java_lang_String_lastIndexOf(env, clazz);
		use_java_lang_String_lastIndexOf_1(env, clazz);
		use_java_lang_String_indexOf_2(env, clazz);
		use_java_lang_String_indexOf_3(env, clazz);
		use_java_lang_String_lastIndexOf_2(env, clazz);
		use_java_lang_String_lastIndexOf_3(env, clazz);
		use_java_lang_String_substring(env, clazz);
		use_java_lang_String_substring_1(env, clazz);
		use_java_lang_String_concat(env, clazz);
		use_java_lang_String_replace(env, clazz);
		use_java_lang_String_toLowerCase(env, clazz);
		use_java_lang_String_toUpperCase(env, clazz);
		use_java_lang_String_trim(env, clazz);
		use_java_lang_String_toString(env, clazz);
		use_java_lang_String_toCharArray(env, clazz);
		use_java_lang_String_valueOf(env, clazz);
		use_java_lang_String_valueOf_1(env, clazz);
		use_java_lang_String_valueOf_2(env, clazz);
		use_java_lang_String_copyValueOf(env, clazz);
		use_java_lang_String_copyValueOf_1(env, clazz);
		use_java_lang_String_valueOf_3(env, clazz);
		use_java_lang_String_valueOf_4(env, clazz);
		use_java_lang_String_valueOf_5(env, clazz);
		use_java_lang_String_valueOf_6(env, clazz);
		use_java_lang_String_valueOf_7(env, clazz);
		use_java_lang_String_valueOf_8(env, clazz);
		use_java_lang_String_intern(env, clazz);
		use_java_lang_String_utfLength(env, clazz);
		_globalclass_java_lang_String = JRI_NewGlobalRef(env, clazz);
		return clazz;
	}
	else {
		return JRI_GetGlobalRef(env, _globalclass_java_lang_String);
	}
}

JRI_PUBLIC_API(void)
unuse_java_lang_String(JRIEnv* env)
{
	if (_globalclass_java_lang_String != NULL) {
		struct java_lang_Class* clazz = JRI_GetGlobalRef(env, _globalclass_java_lang_String);
		unuse_java_lang_String_value(env, clazz);
		unuse_java_lang_String_offset(env, clazz);
		unuse_java_lang_String_count(env, clazz);
		unuse_java_lang_String_InternSet(env, clazz);
		unuse_java_lang_String_new(env, clazz);
		unuse_java_lang_String_new_1(env, clazz);
		unuse_java_lang_String_new_2(env, clazz);
		unuse_java_lang_String_new_3(env, clazz);
		unuse_java_lang_String_new_4(env, clazz);
		unuse_java_lang_String_new_5(env, clazz);
		unuse_java_lang_String_new_6(env, clazz);
		unuse_java_lang_String_new_7(env, clazz);
		unuse_java_lang_String_length(env, clazz);
		unuse_java_lang_String_charAt(env, clazz);
		unuse_java_lang_String_getChars(env, clazz);
		unuse_java_lang_String_getBytes(env, clazz);
		unuse_java_lang_String_equals(env, clazz);
		unuse_java_lang_String_equalsIgnoreCase(env, clazz);
		unuse_java_lang_String_compareTo(env, clazz);
		unuse_java_lang_String_regionMatches(env, clazz);
		unuse_java_lang_String_regionMatches_1(env, clazz);
		unuse_java_lang_String_startsWith(env, clazz);
		unuse_java_lang_String_startsWith_1(env, clazz);
		unuse_java_lang_String_endsWith(env, clazz);
		unuse_java_lang_String_hashCode(env, clazz);
		unuse_java_lang_String_indexOf(env, clazz);
		unuse_java_lang_String_indexOf_1(env, clazz);
		unuse_java_lang_String_lastIndexOf(env, clazz);
		unuse_java_lang_String_lastIndexOf_1(env, clazz);
		unuse_java_lang_String_indexOf_2(env, clazz);
		unuse_java_lang_String_indexOf_3(env, clazz);
		unuse_java_lang_String_lastIndexOf_2(env, clazz);
		unuse_java_lang_String_lastIndexOf_3(env, clazz);
		unuse_java_lang_String_substring(env, clazz);
		unuse_java_lang_String_substring_1(env, clazz);
		unuse_java_lang_String_concat(env, clazz);
		unuse_java_lang_String_replace(env, clazz);
		unuse_java_lang_String_toLowerCase(env, clazz);
		unuse_java_lang_String_toUpperCase(env, clazz);
		unuse_java_lang_String_trim(env, clazz);
		unuse_java_lang_String_toString(env, clazz);
		unuse_java_lang_String_toCharArray(env, clazz);
		unuse_java_lang_String_valueOf(env, clazz);
		unuse_java_lang_String_valueOf_1(env, clazz);
		unuse_java_lang_String_valueOf_2(env, clazz);
		unuse_java_lang_String_copyValueOf(env, clazz);
		unuse_java_lang_String_copyValueOf_1(env, clazz);
		unuse_java_lang_String_valueOf_3(env, clazz);
		unuse_java_lang_String_valueOf_4(env, clazz);
		unuse_java_lang_String_valueOf_5(env, clazz);
		unuse_java_lang_String_valueOf_6(env, clazz);
		unuse_java_lang_String_valueOf_7(env, clazz);
		unuse_java_lang_String_valueOf_8(env, clazz);
		unuse_java_lang_String_intern(env, clazz);
		unuse_java_lang_String_utfLength(env, clazz);
		JRI_DisposeGlobalRef(env, _globalclass_java_lang_String);
		_globalclass_java_lang_String = NULL;
		clazz = NULL;	/* prevent unused variable 'clazz' warning */
	}
}

#endif /* UNUSED_use_java_lang_String */

#ifdef _implementing_java_lang_String

JRI_PUBLIC_API(struct java_lang_Class*)
register_java_lang_String(JRIEnv* env)
{
	char* nativeNamesAndSigs[] = {
		NULL
	};
	void* nativeProcs[] = {
		NULL
	};
	struct java_lang_Class* clazz = JRI_FindClass(env, classname_java_lang_String);
	if (clazz == NULL) {
		JRI_ThrowNew(env, JRI_FindClass(env, "java/lang/ClassNotFoundException"), classname_java_lang_String);
		return NULL;
	}
	JRI_RegisterNatives(env, clazz, nativeNamesAndSigs, nativeProcs);
	use_java_lang_String(env);
	return clazz;
}

JRI_PUBLIC_API(void)
unregister_java_lang_String(JRIEnv* env)
{
	struct java_lang_Class* clazz = JRI_FindClass(env, classname_java_lang_String);
	JRI_UnregisterNatives(env, clazz);
	unuse_java_lang_String(env);
}

#endif /* _implementing_java_lang_String */

/* These stub routines are generated for compatibility with the JDK: */

#ifndef NO_JDK

#endif /* NO_JDK */

