/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jri.h"

/* Stubs for class java/lang/Class */

#ifdef IMPLEMENT_java_lang_Class
#define _implementing_java_lang_Class
#endif /* IMPLEMENT_java_lang_Class */
#define IMPLEMENT_java_lang_Class
#include "java_lang_Class.h"

#ifndef UNUSED_java_lang_Class_new
JRIMethodID FAR methodID_java_lang_Class_new = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct java_lang_Class*)
java_lang_Class_new(JRIEnv* env, struct java_lang_Class* clazz) {
	if (methodID_java_lang_Class_new == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_Class(env) before calling method <init> ()V");
	}
	return (struct java_lang_Class*)JRI_NewObject(env)(env, JRI_NewObject_op, clazz, methodID_java_lang_Class_new);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_Class_new */

#ifndef UNUSED_java_lang_Class_forName
JRIMethodID FAR methodID_java_lang_Class_forName = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct java_lang_Class *)
java_lang_Class_forName(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_String *a) {
	if (methodID_java_lang_Class_forName == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_Class(env) before calling method forName (Ljava/lang/String;)Ljava/lang/Class;");
	}
	return (struct java_lang_Class *)JRI_CallStaticMethod(env)(env, JRI_CallStaticMethod_op, clazz, methodID_java_lang_Class_forName, a);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_Class_forName */

#ifndef UNUSED_java_lang_Class_newInstance
JRIMethodID FAR methodID_java_lang_Class_newInstance = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct java_lang_Object *)
java_lang_Class_newInstance(JRIEnv* env, struct java_lang_Class* self) {
	if (methodID_java_lang_Class_newInstance == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_Class(env) before calling method newInstance ()Ljava/lang/Object;");
	}
	return (struct java_lang_Object *)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_java_lang_Class_newInstance);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_Class_newInstance */

#ifndef UNUSED_java_lang_Class_getName
JRIMethodID FAR methodID_java_lang_Class_getName = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct java_lang_String *)
java_lang_Class_getName(JRIEnv* env, struct java_lang_Class* self) {
	if (methodID_java_lang_Class_getName == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_Class(env) before calling method getName ()Ljava/lang/String;");
	}
	return (struct java_lang_String *)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_java_lang_Class_getName);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_Class_getName */

#ifndef UNUSED_java_lang_Class_getSuperclass
JRIMethodID FAR methodID_java_lang_Class_getSuperclass = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct java_lang_Class *)
java_lang_Class_getSuperclass(JRIEnv* env, struct java_lang_Class* self) {
	if (methodID_java_lang_Class_getSuperclass == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_Class(env) before calling method getSuperclass ()Ljava/lang/Class;");
	}
	return (struct java_lang_Class *)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_java_lang_Class_getSuperclass);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_Class_getSuperclass */

#ifndef UNUSED_java_lang_Class_getInterfaces
JRIMethodID FAR methodID_java_lang_Class_getInterfaces = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jref)
java_lang_Class_getInterfaces(JRIEnv* env, struct java_lang_Class* self) {
	if (methodID_java_lang_Class_getInterfaces == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_Class(env) before calling method getInterfaces ()[Ljava/lang/Class;");
	}
	return (jref)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_java_lang_Class_getInterfaces);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_Class_getInterfaces */

#ifndef UNUSED_java_lang_Class_getClassLoader
JRIMethodID FAR methodID_java_lang_Class_getClassLoader = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct java_lang_ClassLoader *)
java_lang_Class_getClassLoader(JRIEnv* env, struct java_lang_Class* self) {
	if (methodID_java_lang_Class_getClassLoader == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_Class(env) before calling method getClassLoader ()Ljava/lang/ClassLoader;");
	}
	return (struct java_lang_ClassLoader *)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_java_lang_Class_getClassLoader);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_Class_getClassLoader */

#ifndef UNUSED_java_lang_Class_isInterface
JRIMethodID FAR methodID_java_lang_Class_isInterface = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jbool)
java_lang_Class_isInterface(JRIEnv* env, struct java_lang_Class* self) {
	if (methodID_java_lang_Class_isInterface == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_Class(env) before calling method isInterface ()Z");
	}
	return (jbool)JRI_CallMethodBoolean(env)(env, JRI_CallMethod_op, self, methodID_java_lang_Class_isInterface);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_Class_isInterface */

#ifndef UNUSED_java_lang_Class_toString
JRIMethodID FAR methodID_java_lang_Class_toString = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct java_lang_String *)
java_lang_Class_toString(JRIEnv* env, struct java_lang_Class* self) {
	if (methodID_java_lang_Class_toString == JRIUninitialized) {
		assert(!"Forgot to call use_java_lang_Class(env) before calling method toString ()Ljava/lang/String;");
	}
	return (struct java_lang_String *)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_java_lang_Class_toString);
}
#endif /* DEBUG */
#endif /* UNUSED_java_lang_Class_toString */

#ifndef UNUSED_use_java_lang_Class

static jglobal _globalclass_java_lang_Class = NULL;

JRI_PUBLIC_API(struct java_lang_Class*)
use_java_lang_Class(JRIEnv* env)
{
	if (_globalclass_java_lang_Class == NULL) {
		struct java_lang_Class* clazz = JRI_FindClass(env, classname_java_lang_Class);
		if (clazz == NULL) {
			JRI_ThrowNew(env, JRI_FindClass(env, "java/lang/ClassNotFoundException"), classname_java_lang_Class);
			return NULL;
		}
		use_java_lang_Class_new(env, clazz);
		use_java_lang_Class_forName(env, clazz);
		use_java_lang_Class_newInstance(env, clazz);
		use_java_lang_Class_getName(env, clazz);
		use_java_lang_Class_getSuperclass(env, clazz);
		use_java_lang_Class_getInterfaces(env, clazz);
		use_java_lang_Class_getClassLoader(env, clazz);
		use_java_lang_Class_isInterface(env, clazz);
		use_java_lang_Class_toString(env, clazz);
		_globalclass_java_lang_Class = JRI_NewGlobalRef(env, clazz);
		return clazz;
	}
	else {
		return JRI_GetGlobalRef(env, _globalclass_java_lang_Class);
	}
}

JRI_PUBLIC_API(void)
unuse_java_lang_Class(JRIEnv* env)
{
	if (_globalclass_java_lang_Class != NULL) {
		struct java_lang_Class* clazz = JRI_GetGlobalRef(env, _globalclass_java_lang_Class);
		unuse_java_lang_Class_new(env, clazz);
		unuse_java_lang_Class_forName(env, clazz);
		unuse_java_lang_Class_newInstance(env, clazz);
		unuse_java_lang_Class_getName(env, clazz);
		unuse_java_lang_Class_getSuperclass(env, clazz);
		unuse_java_lang_Class_getInterfaces(env, clazz);
		unuse_java_lang_Class_getClassLoader(env, clazz);
		unuse_java_lang_Class_isInterface(env, clazz);
		unuse_java_lang_Class_toString(env, clazz);
		JRI_DisposeGlobalRef(env, _globalclass_java_lang_Class);
		_globalclass_java_lang_Class = NULL;
		clazz = NULL;	/* prevent unused variable 'clazz' warning */
	}
}

#endif /* UNUSED_use_java_lang_Class */

#ifdef _implementing_java_lang_Class

JRI_PUBLIC_API(struct java_lang_Class*)
register_java_lang_Class(JRIEnv* env)
{
	char* nativeNamesAndSigs[] = {
		"forName(Ljava/lang/String;)Ljava/lang/Class;",
		"newInstance()Ljava/lang/Object;",
		"getName()Ljava/lang/String;",
		"getSuperclass()Ljava/lang/Class;",
		"getInterfaces()[Ljava/lang/Class;",
		"getClassLoader()Ljava/lang/ClassLoader;",
		"isInterface()Z",
		NULL
	};
	void* nativeProcs[] = {
		(void*)native_java_lang_Class_forName,
		(void*)native_java_lang_Class_newInstance,
		(void*)native_java_lang_Class_getName,
		(void*)native_java_lang_Class_getSuperclass,
		(void*)native_java_lang_Class_getInterfaces,
		(void*)native_java_lang_Class_getClassLoader,
		(void*)native_java_lang_Class_isInterface,
		NULL
	};
	struct java_lang_Class* clazz = JRI_FindClass(env, classname_java_lang_Class);
	if (clazz == NULL) {
		JRI_ThrowNew(env, JRI_FindClass(env, "java/lang/ClassNotFoundException"), classname_java_lang_Class);
		return NULL;
	}
	JRI_RegisterNatives(env, clazz, nativeNamesAndSigs, nativeProcs);
	use_java_lang_Class(env);
	return clazz;
}

JRI_PUBLIC_API(void)
unregister_java_lang_Class(JRIEnv* env)
{
	struct java_lang_Class* clazz = JRI_FindClass(env, classname_java_lang_Class);
	JRI_UnregisterNatives(env, clazz);
	unuse_java_lang_Class(env);
}

#endif /* _implementing_java_lang_Class */

/* These stub routines are generated for compatibility with the JDK: */

#ifndef NO_JDK

/* SYMBOL: "java/lang/Class/forName(Ljava/lang/String;)Ljava/lang/Class;", Java_java_lang_Class_forName_stub */
JRI_PUBLIC_API(JRI_JDK_stack_item*)
Java_java_lang_Class_forName_stub(JRI_JDK_stack_item* _P_, JRIEnv* _EE_) {
	_P_[0].p = native_java_lang_Class_forName(_EE_,NULL,((_P_[0].p)));
	return _P_ + 1;
}

/* SYMBOL: "java/lang/Class/newInstance()Ljava/lang/Object;", Java_java_lang_Class_newInstance_stub */
JRI_PUBLIC_API(JRI_JDK_stack_item*)
Java_java_lang_Class_newInstance_stub(JRI_JDK_stack_item* _P_, JRIEnv* _EE_) {
	_P_[0].p = native_java_lang_Class_newInstance(_EE_,_P_[0].p);
	return _P_ + 1;
}

/* SYMBOL: "java/lang/Class/getName()Ljava/lang/String;", Java_java_lang_Class_getName_stub */
JRI_PUBLIC_API(JRI_JDK_stack_item*)
Java_java_lang_Class_getName_stub(JRI_JDK_stack_item* _P_, JRIEnv* _EE_) {
	_P_[0].p = native_java_lang_Class_getName(_EE_,_P_[0].p);
	return _P_ + 1;
}

/* SYMBOL: "java/lang/Class/getSuperclass()Ljava/lang/Class;", Java_java_lang_Class_getSuperclass_stub */
JRI_PUBLIC_API(JRI_JDK_stack_item*)
Java_java_lang_Class_getSuperclass_stub(JRI_JDK_stack_item* _P_, JRIEnv* _EE_) {
	_P_[0].p = native_java_lang_Class_getSuperclass(_EE_,_P_[0].p);
	return _P_ + 1;
}

/* SYMBOL: "java/lang/Class/getInterfaces()[Ljava/lang/Class;", Java_java_lang_Class_getInterfaces_stub */
JRI_PUBLIC_API(JRI_JDK_stack_item*)
Java_java_lang_Class_getInterfaces_stub(JRI_JDK_stack_item* _P_, JRIEnv* _EE_) {
	_P_[0].p = native_java_lang_Class_getInterfaces(_EE_,_P_[0].p);
	return _P_ + 1;
}

/* SYMBOL: "java/lang/Class/getClassLoader()Ljava/lang/ClassLoader;", Java_java_lang_Class_getClassLoader_stub */
JRI_PUBLIC_API(JRI_JDK_stack_item*)
Java_java_lang_Class_getClassLoader_stub(JRI_JDK_stack_item* _P_, JRIEnv* _EE_) {
	_P_[0].p = native_java_lang_Class_getClassLoader(_EE_,_P_[0].p);
	return _P_ + 1;
}

/* SYMBOL: "java/lang/Class/isInterface()Z", Java_java_lang_Class_isInterface_stub */
JRI_PUBLIC_API(JRI_JDK_stack_item*)
Java_java_lang_Class_isInterface_stub(JRI_JDK_stack_item* _P_, JRIEnv* _EE_) {
	_P_[0].i = (native_java_lang_Class_isInterface(_EE_,_P_[0].p) ? 1 : 0);
	return _P_ + 1;
}

#endif /* NO_JDK */

